annotations:
  artifacthub.io/category: networking
  artifacthub.io/license: MIT License
  artifacthub.io/images: |
    - name: stunner
      image: docker.io/l7mp/stunnerd:1.0.0
    - name: stunner-gateway-operator
      image: docker.io/l7mp/stunner-gateway-operator:1.0.0
    - name: stunner-auth-server
      image: docker.io/l7mp/stunner-auth-server:1.0.0
    - name: kube-rbac-proxy
      image: gcr.io/kubebuilder/kube-rbac-proxy:v0.16.0
    - name: stunner-gateway-operator-premium
      image: docker.io/l7mp/stunner-gateway-operator-premium:dev
    - name: stunnerd-premium
      image: docker.io/l7mp/stunnerd-premium:dev


apiVersion: v2
name: stunner-gateway-operator
description: STUNner Kubernetes Gateway Operator
maintainers:
  - name: l7mp
    email: info@l7mp.io
    url: https://l7mp.io
icon: https://raw.githubusercontent.com/l7mp/stunner/main/docs/img/stunner.svg
type: application
version: 1.1.0
appVersion: 1.1.0
